services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik

  tedx-fe:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tedx-fe.rule=Host(`tedxuniversitasbrawijaya.org` || `www.tedxuniversitasbrawijaya.org`)"
      - "traefik.http.routers.tedx-fe.entrypoints=web"
    networks:
      - traefik
    restart: always

networks:
  traefik:
    driver: bridge
