services:
  reverse-proxy:
    container_name: tedx-fe-proxy
    image: traefik:v3.1
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik

  tedx-fe:
    container_name: tedx-fe
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.tedx-fe.rule=Host(`tedxuniversitasbrawijaya.org`) || Host(`www.tedxuniversitasbrawijaya.org`) || Host(`localhost`)"
      - "traefik.http.routers.tedx-fe.entrypoints=web"
      - "traefik.http.services.tedx-fe.loadbalancer.server.port=3000"
    networks:
      - traefik
    restart: always

networks:
  traefik:
    driver: bridge
