export const keywords = [
  "TEDxUniversitasBrawijaya",
  "TEDxUniversitasBrawijaya 2025",
  "TEDx",
  "TEDx Jatim",
  "TEDx Jawa Timur",
  "TEDx Malang",
  "TEDx UB",
  "TEDxUB",
  "TEDxUB 2025",
  "TEDx Universitas Brawijaya 2025",
  "TEDx events in Indonesia",
  "TEDx Malang 2025",
  "TEDx Propaganda 3",
  "TEDx Main Event",
  "Mantra Djiwa",
  "TEDx Jawa Timur",
  "Inspirational talks Malang",
  "TEDx Universitas Brawijaya tickets",
  "Join TEDx 2025",
  "TED talks Universitas Brawijaya",
  "Book TEDx tickets Malang",
  "TEDx ticket",
  "TEDx tiket",
  "Universitas Brawijaya events",
  "Universitas Brawijaya",
  "UB",
  "Malang",
  "Jatim",
];
